#1. 서버 설정
server:
  port: 9000
#  기본값은 8080
#2. 스프링 관련 설정
spring:
  datasource: #http://locahost:8080/h2-console
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    #h2 콘솔환경
  h2:
    console:
    enabled: true
  jpa:
    hibernate: #JPA entity에 따라 DB 스키마가 업데이트 된다ㅓ.
    ddl-auto: update #none, validate, update, create, and create-drop 등의 옵션을 가진다.
    show-sql: true # SQL문 출력 정렬 해줘!!